import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.*;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author asus
 */
public class pelanggan extends javax.swing.JFrame {
     int harga_kamar;
     int jumlah,Total;
     int jumlah_hari;
     int jumlah_kamar;
     String tipe_kamar,bulan;
  
public void hitung(){
   int a,b;
   a=Integer.parseInt(txt_hari.getText());
   b=Integer.parseInt(txt_hari2.getText());
   int hasil=b-a;
   txt_la.setText(String.valueOf(hasil));
   }    

public void hitung1(){
int a,b,hasil;
a=Integer.parseInt(txt_total.getText());
b=Integer.parseInt(txt_duit.getText());
hasil=a-b;
txt_kembali.setText(String.valueOf(hasil));
}

public void hitung2(){
int masuk = Integer.parseInt(txt_la.getText());
   int keluar = Integer.parseInt(txt_hari2.getText());
   int kamar  = Integer.parseInt(txt_jumlah.getText());
if(cbStandar.isSelected()){
    harga_kamar=100000; 
}else if(cbSuperior.isSelected()){
    harga_kamar=200000;
}else if(cbPresidential.isSelected()){
    harga_kamar=300000;
}
int hasil = masuk*harga_kamar*kamar;
txt_total.setText(String.valueOf(hasil));
}
     
    /**
     * Creates new form NewJFrame
     */
    public pelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollBar1 = new javax.swing.JScrollBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tipe_kamar1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_identitas = new javax.swing.JTextField();
        txt_tahun = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        btn_sp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        txt_hari2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_hps = new javax.swing.JButton();
        cbStandar = new javax.swing.JCheckBox();
        cbSuperior = new javax.swing.JCheckBox();
        txt_hari = new javax.swing.JTextField();
        txt_bulan = new javax.swing.JComboBox<>();
        txt_tahun2 = new javax.swing.JTextField();
        txt_bulan2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_la = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_duit = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_kembali = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbPresidential = new javax.swing.JCheckBox();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAMA");

        jLabel2.setText("NOMOR IDENTITAS");

        jLabel3.setText("TGL CHEK IN");

        tipe_kamar1.setText("TIPE KAMAR");

        txt_identitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_identitasActionPerformed(evt);
            }
        });
        txt_identitas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_identitasKeyPressed(evt);
            }
        });

        txt_tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tahunActionPerformed(evt);
            }
        });

        txt_total.setEditable(false);
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        btn_sp.setText("SIMPAN");
        btn_sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_spActionPerformed(evt);
            }
        });

        jLabel6.setText("JUMLAH KAMAR");

        jLabel7.setText("TGL CHEKOUT");

        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });

        txt_hari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hari2ActionPerformed(evt);
            }
        });
        txt_hari2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hari2KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("INPUT PELANGGAN");

        btn_hps.setText("DELETE");
        btn_hps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hpsActionPerformed(evt);
            }
        });

        cbStandar.setText("1.STANDART (Rp.100.000.00,-/hari)");
        cbStandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStandarActionPerformed(evt);
            }
        });

        cbSuperior.setText("2.SUPERIOR (Rp.200.000.00,00-/hari)");
        cbSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSuperiorActionPerformed(evt);
            }
        });

        txt_bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Bulan--", "Januari", "Februari", "Maret", "April", "Mei ", "Juni", "Juli ", "Agustus", "September", "Oktober", "November", "Desember" }));

        txt_bulan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Bulan--", "Januari", "Februari", "Maret", "April", "Mei ", "Juni", "Juli ", "Agustus", "September", "Oktober", "November", "Desember" }));

        jLabel9.setText("TOTAL");

        txt_la.setEditable(false);

        jLabel5.setText("LAMA MENGINAP");

        jLabel10.setText("hari");

        txt_duit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_duitKeyReleased(evt);
            }
        });

        jLabel11.setText("UANG MUKA");

        jLabel4.setText("Rp:");

        jLabel12.setText("Rp:");

        txt_kembali.setEditable(false);
        txt_kembali.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_kembaliKeyReleased(evt);
            }
        });

        jLabel13.setText("UANG ANDA");

        jLabel14.setText("Rp:");

        jButton1.setText("KELUAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbPresidential.setText("3.PRESIDENTIAL (Rp.300.000.00,-/hari)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_bulan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_tahun2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txt_identitas, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                            .addComponent(txt_nama)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txt_hari)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_la, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10))
                                            .addComponent(txt_hari2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_duit, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbStandar)
                                    .addComponent(cbSuperior)
                                    .addComponent(cbPresidential)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(tipe_kamar1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(btn_sp)
                                .addGap(48, 48, 48)
                                .addComponent(btn_hps)
                                .addGap(49, 49, 49)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_identitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_hari2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bulan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tahun2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_la, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(5, 5, 5)
                .addComponent(tipe_kamar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbStandar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSuperior)
                .addGap(3, 3, 3)
                .addComponent(cbPresidential)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_duit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sp)
                    .addComponent(btn_hps)
                    .addComponent(jButton1))
                .addGap(85, 85, 85))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_identitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_identitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_identitasActionPerformed

    private void txt_tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tahunActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed

    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void btn_spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_spActionPerformed
    if(cbStandar.isSelected()){
    tipe_kamar="standar";
    }else if(cbSuperior.isSelected()){
    tipe_kamar="superior";    
    } else if(cbPresidential.isSelected()){
        tipe_kamar="presidential";
    }
    if(txt_identitas.getText().isEmpty() || txt_nama.getText().isEmpty() || txt_hari.getText().isEmpty() || 
            txt_jumlah.getText().isEmpty() || txt_hari2.getText().isEmpty() || txt_total.getText().isEmpty() ||
            txt_duit.getText().isEmpty() || txt_kembali.getText().isEmpty())
        
        JOptionPane.showMessageDialog(this,"semua kolom harus terisis","pesan",JOptionPane.WARNING_MESSAGE);
    
    try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql:"+"///data_pelanggan","root","");
            Statement smt =cn.createStatement();
          
            smt.executeUpdate(
            "insert into plg (nomor_identitas,nama,tgl_checkin,lama_menginap,tipe_kamar,jumlah_kamar,tgl_checkout,total,uang_muka,uang_anda) values" + "('"+                
                    txt_identitas.getText()+"',"+"'"+
                    txt_nama.getText()+"',"+"'"+
                    txt_hari.getText()+txt_bulan.getSelectedItem()+txt_tahun.getText()+"',"+"'"+
                    txt_la.getText()+"',"+"'"+
                    tipe_kamar+"',"+"'"+
                    txt_jumlah.getText()+"',"+"'"+
                    txt_hari2.getText()+txt_bulan2.getSelectedItem()+txt_tahun2.getText()+"',"+"'"+   
                    txt_total.getText()+"',"+"'"+
                    txt_duit.getText()+"',"+"'"+
                    txt_kembali.getText()+"')");
            txt_identitas.requestFocus();
            
            JOptionPane.showMessageDialog(this,"data telah di simpan:)",
                "pesan",JOptionPane.INFORMATION_MESSAGE);
                           
            txt_nama.setText("");
            txt_identitas.setText("");
            txt_tahun.setText("");
            txt_hari.setText("");
            txt_tahun2.setText("");
            txt_hari2.setText("");
            txt_duit.setText("");
            txt_kembali.setText("");
            txt_la.setText("");
            txt_jumlah.setText("");
            txt_hari2.setText("");
            txt_total.setText("");
            txt_identitas.requestFocus();
    }catch (Exception e) {
        e.printStackTrace();
        
    }      
    }//GEN-LAST:event_btn_spActionPerformed

    private void txt_identitasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_identitasKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql:"+"///data_pelanggan","root","");
            Statement smt =cn.createStatement();
            ResultSet rs = smt.executeQuery("SELECT * FROM plg where nomor_identitas = '"+txt_identitas.getText()+"'");
            if(rs.next()){
            txt_identitas.setText(rs.getString("nomor_identitas"));    
            txt_nama.setText(rs.getString("nama"));
            txt_hari.setText(rs.getString("tgl_checkin")); 
            txt_jumlah.setText(rs.getString("jumlah_kamar"));
            txt_hari2.setText(rs.getString("tgl_checkout"));
            txt_la.setText(rs.getString("lama_menginap"));
            txt_total.setText(rs.getString("total"));
            txt_duit.setText(rs.getString("uang_muka"));
            txt_kembali.setText(rs.getString("uang_anda"));
        
            }else{
                JOptionPane.showMessageDialog(this,"data tidak ada",
                        "pesan",JOptionPane.INFORMATION_MESSAGE);
            }
            
            }catch(Exception e){
                e.printStackTrace();
        }
    }            
    }//GEN-LAST:event_txt_identitasKeyPressed

    private void btn_hpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hpsActionPerformed
    if(txt_identitas.getText().isEmpty() || txt_nama.getText().isEmpty() || txt_hari.getText().isEmpty() || 
            txt_jumlah.getText().isEmpty() || txt_hari2.getText().isEmpty() || txt_total.getText().isEmpty() ||
            txt_duit.getText().isEmpty() || txt_kembali.getText().isEmpty())
        
        JOptionPane.showMessageDialog(this,"masukan data !!","pesan",JOptionPane.WARNING_MESSAGE);
    
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = DriverManager.getConnection("jdbc:mysql:"+"///data_pelanggan","root","");
            Statement smt =cn.createStatement();
            smt.executeUpdate("Delete from plg where nomor_identitas='"+txt_identitas.getText()+"'");
            
          
            JOptionPane.showMessageDialog(this,"data telah di hapus :v",
                "pesan",JOptionPane.INFORMATION_MESSAGE);
                    
            txt_nama.setText("");
            txt_identitas.setText("");
            txt_tahun.setText("");
            txt_jumlah.setText("");
            txt_hari2.setText("");
            txt_total.setText("");
            txt_identitas.requestFocus();
            
    }catch (Exception e) {
        e.printStackTrace();
    }                      
    }//GEN-LAST:event_btn_hpsActionPerformed

    private void cbSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSuperiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSuperiorActionPerformed

    private void cbStandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStandarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStandarActionPerformed

    private void txt_hari2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hari2KeyReleased
      hitung();
    }//GEN-LAST:event_txt_hari2KeyReleased

    private void txt_hari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hari2ActionPerformed

    private void txt_kembaliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kembaliKeyReleased

    }//GEN-LAST:event_txt_kembaliKeyReleased

    private void txt_duitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_duitKeyReleased
    hitung1();
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_duitKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    System.exit(0);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
    hitung2();
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    this.setVisible(false);
        new menu().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hps;
    private javax.swing.JButton btn_sp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbPresidential;
    private javax.swing.JCheckBox cbStandar;
    private javax.swing.JCheckBox cbSuperior;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel tipe_kamar1;
    private javax.swing.JComboBox<String> txt_bulan;
    private javax.swing.JComboBox<String> txt_bulan2;
    private javax.swing.JTextField txt_duit;
    private javax.swing.JTextField txt_hari;
    private javax.swing.JTextField txt_hari2;
    private javax.swing.JTextField txt_identitas;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_kembali;
    private javax.swing.JTextField txt_la;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tahun;
    private javax.swing.JTextField txt_tahun2;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

    private void add(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
